# Generated by Django 4.0.2 on 2022-02-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='geulnoon',
            fields=[
                ('email', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=15, null=True)),
                ('birthyear', models.IntegerField()),
            ],
        ),
    ]
