# Generated by Django 4.0.2 on 2022-02-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geulnoon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=60)),
                ('birthyear', models.TextField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='geulnoon',
        ),
    ]
